export default {
  data: [
    {
      id: 1,
      type: "Shirt",
      size: "M",
      color: "Blue",
      name: "Casual Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.5,
      img_src: "eCommerce/assets/black-t-shirt.jpg",
      price: "$39.99",
      number_of_reviews: 150,
      short_description: "Stylish and comfy",
    },
    {
      id: 2,
      type: "Shirt",
      size: "L",
      color: "Red",
      name: "Formal Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.2,
      // img_src: "eCommerce/assets/comfort-t-shirt.jpg",
      img_src: "eCommerce/assets/test.png",
      price: "$49.99",
      number_of_reviews: 200,
      short_description: "Elegant look",
    },
    {
      id: 3,
      type: "Shirt",
      size: "S",
      color: "Green",
      name: "Hawaiian Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 3.8,
      img_src: "eCommerce/assets/shirt1.jpg",
      price: "$59.99",
      number_of_reviews: 120,
      short_description: "Trendy design",
    },
    {
      id: 4,
      type: "Shirt",
      size: "XL",
      color: "Yellow",
      name: "Summer Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.0,
      img_src: "eCommerce/assets/shirt2.jpg",
      price: "$42.99",
      number_of_reviews: 180,
      short_description: "Comfortable fit",
    },
    {
      id: 5,
      type: "Shirt",
      size: "M",
      color: "White",
      name: "Linen Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.1,
      img_src: "eCommerce/assets/shirt3.jpg",
      price: "$69.99",
      number_of_reviews: 140,
      short_description: "High quality",
    },
    {
      id: 6,
      type: "Shirt",
      size: "XXL",
      color: "Black",
      name: "Denim Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 3.9,
      img_src: "eCommerce/assets/shirt4.jpg",
      price: "$89.99",
      number_of_reviews: 160,
      short_description: "Durable and stylish",
    },
    {
      id: 7,
      type: "Shirt",
      size: "L",
      color: "Pink",
      name: "Party Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.3,
      img_src: "eCommerce/assets/shirt5.jpg",
      price: "$79.99",
      number_of_reviews: 220,
      short_description: "Festive look",
    },
    {
      id: 8,
      type: "Shirt",
      size: "M",
      color: "Purple",
      name: "Polo Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 3.7,
      img_src: "eCommerce/assets/shirt6.jpg",
      price: "$45.99",
      number_of_reviews: 170,
      short_description: "Classic design",
    },
    {
      id: 9,
      type: "Shirt",
      size: "S",
      color: "Orange",
      name: "Sport Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.6,
      img_src: "eCommerce/assets/shirt7.jpg",
      price: "$65.99",
      number_of_reviews: 250,
      short_description: "Sporty and comfy",
    },
    {
      id: 10,
      type: "Shirt",
      size: "XL",
      color: "Gray",
      name: "Golf Shirt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.0,
      img_src: "eCommerce/assets/shirt8.jpg",
      price: "$55.99",
      number_of_reviews: 130,
      short_description: "Comfortable fit",
    },
    {
      id: 11,
      type: "Pants",
      size: "M",
      color: "Blue",
      name: "Jeans",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.5,
      img_src: "eCommerce/assets/dress-pants.jpg",
      price: "$99.99",
      number_of_reviews: 300,
      short_description: "Stylish and comfy",
    },
    {
      id: 12,
      type: "Pants",
      size: "L",
      color: "Black",
      name: "Chinos",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.1,
      img_src: "eCommerce/assets/pants2.jpg",
      price: "$78.79",
      number_of_reviews: 999,
      short_description: "Comfortable fit",
    },
    {
      id: 13,
      type: "Pants",
      size: "L",
      color: "White",
      name: "Shorts",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 2.4,
      img_src: "eCommerce/assets/pants3.jpg",
      price: "$79.11",
      number_of_reviews: 868,
      short_description: "Trendy design",
    },
    {
      id: 14,
      type: "Pants",
      size: "S",
      color: "Yellow",
      name: "Shorts",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 1.7,
      img_src: "eCommerce/assets/pants4.jpg",
      price: "$218.50",
      number_of_reviews: 654,
      short_description: "Stylish and comfy",
    },
    {
      id: 15,
      type: "Pants",
      size: "S",
      color: "White",
      name: "Chinos",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 2.8,
      img_src: "eCommerce/assets/pants5.jpg",
      price: "$51.62",
      number_of_reviews: 546,
      short_description: "Comfortable fit",
    },
    {
      id: 16,
      type: "Pants",
      size: "XL",
      color: "White",
      name: "Jeans",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 2.2,
      img_src: "eCommerce/assets/pants6.jpg",
      price: "$190.85",
      number_of_reviews: 539,
      short_description: "Stylish and comfy",
    },
    {
      id: 17,
      type: "Pants",
      size: "M",
      color: "Yellow",
      name: "Joggers",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.2,
      img_src: "eCommerce/assets/pants7.jpg",
      price: "$230.92",
      number_of_reviews: 252,
      short_description: "Comfortable fit",
    },
    {
      id: 18,
      type: "Pants",
      size: "S",
      color: "Purple",
      name: "Khakis",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.2,
      img_src: "eCommerce/assets/pants8.jpg",
      price: "$240.79",
      number_of_reviews: 33,
      short_description: "High quality",
    },
    {
      id: 19,
      type: "Pants",
      size: "XL",
      color: "Blue",
      name: "Joggers",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 1.2,
      img_src: "eCommerce/assets/pants9.jpg",
      price: "$120.26",
      number_of_reviews: 88,
      short_description: "Trendy design",
    },
    {
      id: 20,
      type: "Pants",
      size: "M",
      color: "White",
      name: "Khakis",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 1.6,
      img_src: "eCommerce/assets/pants10.jpg",
      price: "$180.68",
      number_of_reviews: 865,
      short_description: "High quality",
    },
    {
      id: 21,
      type: "Pants",
      size: "S",
      color: "Blue",
      name: "Shorts",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 3.4,
      img_src: "eCommerce/assets/pants11.jpg",
      price: "$138.96",
      number_of_reviews: 13,
      short_description: "Comfortable fit",
    },
    {
      id: 22,
      type: "Pants",
      size: "S",
      color: "Yellow",
      name: "Joggers",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 1.6,
      img_src: "eCommerce/assets/pants12.jpg",
      price: "$136.72",
      number_of_reviews: 233,
      short_description: "Stylish and comfy",
    },
    {
      id: 23,
      type: "Pants",
      size: "XXL",
      color: "Purple",
      name: "Jeans",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.9,
      img_src: "eCommerce/assets/pants13.jpg",
      price: "$199.95",
      number_of_reviews: 435,
      short_description: "Comfortable fit",
    },
    {
      id: 24,
      type: "Pants",
      size: "L",
      color: "Yellow",
      name: "Khakis",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 2.2,
      img_src: "eCommerce/assets/pants14.jpg",
      price: "$63.73",
      number_of_reviews: 198,
      short_description: "Comfortable fit",
    },
    {
      id: 25,
      type: "Pants",
      size: "XXL",
      color: "Purple",
      name: "Jeans",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.2,
      img_src: "eCommerce/assets/pants15.jpg",
      price: "$84.36",
      number_of_reviews: 949,
      short_description: "Comfortable fit",
    },
    {
      id: 26,
      type: "Shoes",
      size: "7",
      color: "Black",
      name: "Sneakers",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.7,
      img_src: "eCommerce/assets/shoes1.jpg",
      price: "$120.99",
      number_of_reviews: 250,
      short_description: "Trendy design",
    },
    {
      id: 27,
      type: "Shoes",
      size: "8",
      color: "White",
      name: "Running Shoes",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.8,
      img_src: "eCommerce/assets/shoes2.jpg",
      price: "$139.99",
      number_of_reviews: 280,
      short_description: "Comfortable fit",
    },
    {
      id: 28,
      type: "Shoes",
      size: "9",
      color: "Red",
      name: "Loafers",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.2,
      img_src: "eCommerce/assets/shoes3.jpg",
      price: "$159.99",
      number_of_reviews: 220,
      short_description: "Stylish and comfy",
    },
    {
      id: 29,
      type: "Shoes",
      size: "10",
      color: "Blue",
      name: "Boots",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.0,
      img_src: "eCommerce/assets/shoes4.jpg",
      price: "$179.99",
      number_of_reviews: 180,
      short_description: "Durable and stylish",
    },
    {
      id: 30,
      type: "Shoes",
      size: "11",
      color: "Green",
      name: "Sandals",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.5,
      img_src: "eCommerce/assets/shoes5.jpg",
      price: "$99.99",
      number_of_reviews: 150,
      short_description: "High quality",
    },
    {
      id: 31,
      type: "Shoes",
      size: "12",
      color: "Brown",
      name: "Dress Shoes",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.6,
      img_src: "eCommerce/assets/shoes6.jpg",
      price: "$199.99",
      number_of_reviews: 300,
      short_description: "Elegant look",
    },
    {
      id: 32,
      type: "Shoes",
      size: "13",
      color: "Yellow",
      name: "Casual Shoes",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.1,
      img_src: "eCommerce/assets/shoes7.jpg",
      price: "$89.99",
      number_of_reviews: 120,
      short_description: "Classic design",
    },
    {
      id: 33,
      type: "Shoes",
      size: "7",
      color: "Black",
      name: "Sneakers",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.3,
      img_src: "eCommerce/assets/shoes8.jpg",
      price: "$149.99",
      number_of_reviews: 200,
      short_description: "Stylish and comfy",
    },
    {
      id: 34,
      type: "Shoes",
      size: "8",
      color: "White",
      name: "Running Shoes",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.7,
      img_src: "eCommerce/assets/shoes9.jpg",
      price: "$169.99",
      number_of_reviews: 280,
      short_description: "Sporty and comfy",
    },
    {
      id: 35,
      type: "Shoes",
      size: "9",
      color: "Red",
      name: "Loafers",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.4,
      img_src: "eCommerce/assets/shoes10.jpg",
      price: "$189.99",
      number_of_reviews: 220,
      short_description: "Trendy design",
    },
    {
      id: 36,
      type: "Accessories",
      size: "M",
      color: "Black",
      name: "Belt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.8,
      img_src: "eCommerce/assets/belt.jpg",
      price: "$49.99",
      number_of_reviews: 320,
      short_description: "Durable and stylish",
    },
    {
      id: 37,
      type: "Accessories",
      size: "L",
      color: "Brown",
      name: "Wallet",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.9,
      img_src: "eCommerce/assets/wallet.jpg",
      price: "$59.99",
      number_of_reviews: 280,

      short_description: "High quality",
    },
    {
      id: 38,
      type: "Accessories",
      size: "S",
      color: "Blue",
      name: "Hat",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.5,
      img_src: "eCommerce/assets/hat.jpg",
      price: "$39.99",
      number_of_reviews: 220,
      short_description: "Trendy design",
    },
    {
      id: 39,
      type: "Accessories",
      size: "XL",
      color: "Red",
      name: "Scarf",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.6,
      img_src: "eCommerce/assets/scarf.jpg",
      price: "$69.99",
      number_of_reviews: 150,
      short_description: "Comfortable fit",
    },
    {
      id: 40,
      type: "Accessories",
      size: "M",
      color: "Green",
      name: "Sunglasses",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.7,
      img_src: "eCommerce/assets/sunglasses.jpg",
      price: "$79.99",
      number_of_reviews: 200,
      short_description: "Elegant look",
    },
    {
      id: 41,
      type: "Accessories",
      size: "XXL",
      color: "Yellow",
      name: "Gloves",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.8,
      img_src: "eCommerce/assets/gloves.jpg",
      price: "$89.99",
      number_of_reviews: 170,
      short_description: "High quality",
    },
    {
      id: 42,
      type: "Accessories",
      size: "S",
      color: "Purple",
      name: "Tie",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.9,
      img_src: "eCommerce/assets/tie.jpg",
      price: "$49.99",
      number_of_reviews: 220,
      short_description: "Classic design",
    },
    {
      id: 43,
      type: "Accessories",
      size: "L",
      color: "Blue",
      name: "Watch",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.7,
      img_src: "eCommerce/assets/watch.jpg",
      price: "$249.99",
      number_of_reviews: 180,
      short_description: "Durable and stylish",
    },
    {
      id: 44,
      type: "Accessories",
      size: "M",
      color: "Black",
      name: "Belt",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.8,
      img_src: "eCommerce/assets/belt 2.jpg",
      price: "$49.99",
      number_of_reviews: 320,
      short_description: "Durable and stylish",
    },
    {
      id: 45,
      type: "Accessories",
      size: "L",
      color: "Brown",
      name: "Wallet",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.9,
      img_src: "eCommerce/assets/wallet2.jpg",
      price: "$59.99",
      number_of_reviews: 280,
      short_description: "High quality",
    },
    {
      id: 46,
      type: "Accessories",
      size: "S",
      color: "Blue",
      name: "Hat",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.5,
      img_src: "eCommerce/assets/hat2.jpg",
      price: "$39.99",
      number_of_reviews: 220,
      short_description: "Trendy design",
    },
    {
      id: 47,
      type: "Accessories",
      size: "XL",
      color: "Red",
      name: "Scarf",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.6,
      img_src: "eCommerce/assets/scarf2.jpg",
      price: "$69.99",
      number_of_reviews: 150,
      short_description: "Comfortable fit",
    },
    {
      id: 48,
      type: "Accessories",
      size: "M",
      color: "Green",
      name: "Sunglasses",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.7,
      img_src: "eCommerce/assets/sunglasses2.jpg",
      price: "$79.99",
      number_of_reviews: 200,
      short_description: "Elegant look",
    },
    {
      id: 49,
      type: "Accessories",
      size: "XXL",
      color: "Yellow",
      name: "Gloves",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.8,
      img_src: "eCommerce/assets/gloves2.jpg",
      price: "$89.99",
      number_of_reviews: 170,
      short_description: "High quality",
    },
    {
      id: 50,
      type: "Accessories",
      size: "S",
      color: "Purple",
      name: "Tie",
      description:
        "This product is made from high-quality materials and designed to provide comfort and style. Perfect for any occasion.",
      ratings: 4.9,
      img_src: "eCommerce/assets/tie2.jpg",
      price: "$49.99",
      number_of_reviews: 220,
      short_description: "Classic design",
    },
  ],
};
